"""HTTP API (spec section 14). OpenAPI generated by FastAPI is the UI contract."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Literal

from fastapi import APIRouter, File, Form, HTTPException, Query, Request, UploadFile
from fastapi.responses import Response
from pydantic import BaseModel, Field

from invoice_analytics import ENGINE_VERSION
from invoice_analytics.api.deps import Admin, Reviewer, Viewer, get_engine, get_sessions
from invoice_analytics.context import Engine
from invoice_analytics.security import audit
from invoice_analytics.security.users import AuthError, Session, create_user, primary_admin_id, user_count

router = APIRouter()


def E(request: Request) -> Engine:  # noqa: N802
    return get_engine(request)


def _j(v: Any) -> Any:
    return json.loads(v) if isinstance(v, str) and v[:1] in "[{" else v


# ====================================================================== health / setup / auth
@router.get("/health", tags=["system"])
def health(request: Request) -> dict[str, Any]:
    eng = E(request)
    return {"status": "ok", "engine_version": ENGINE_VERSION, "needs_setup": user_count(eng.db) == 0}


class SetupAdmin(BaseModel):
    username: str = Field(min_length=2, max_length=64)
    display_name: str = Field(min_length=1, max_length=120)
    password: str = Field(min_length=10, max_length=256)
    create_recovery_key: bool = True


@router.get("/setup/status", tags=["system"])
def setup_status(request: Request) -> dict[str, Any]:
    from invoice_analytics.ai import hardware

    eng = E(request)
    return {"needs_admin": user_count(eng.db) == 0, "hardware": hardware.detect(), "data_dir": str(eng.config.data_dir)}


@router.post("/setup/admin", tags=["system"])
def setup_admin(body: SetupAdmin, request: Request) -> dict[str, Any]:
    from invoice_analytics.security.crypto import new_recovery_key
    from invoice_analytics.security.keystore import Keystore

    eng = E(request)
    with eng.db.write_lock:
        if user_count(eng.db) > 0:
            raise HTTPException(409, "setup already completed")
        uid = create_user(eng.db, body.username, body.display_name, "ADMIN", body.password)
    rk = None
    if body.create_recovery_key:
        rk = new_recovery_key()
        Keystore(eng.config.data_dir, eng.config.keystore).write_recovery(eng.keys, rk)
        audit.record(eng.db, "RECOVERY_KEY_CREATED", user_id=uid, entity_type="keystore")
    return {
        "user_id": uid,
        "recovery_key": rk,
        "recovery_key_notice": (
            "Shown once. Print it and store it securely; it can restore backups on a new machine." if rk else None
        ),
    }


class Login(BaseModel):
    username: str
    password: str


@router.get("/auth/mode", tags=["auth"])
def auth_mode(request: Request) -> dict[str, Any]:
    return {"require_login": bool(E(request).settings.get("security.require_login", False))}


@router.post("/auth/auto", tags=["auth"])
def auth_auto(request: Request) -> dict[str, Any]:
    """Sign in as the primary admin without a password, only when sign-in is not required.
    The per-launch bearer token still protects this endpoint from other local processes."""
    eng = E(request)
    if eng.settings.get("security.require_login", False):
        raise HTTPException(403, "sign-in is required")
    with eng.db.write_lock:
        uid = primary_admin_id(eng.db)
    s = get_sessions(request).open_session(uid, idle_seconds=0)
    return {"session_token": s.token, "user": s.as_dict(), "idle_seconds": 0}


@router.post("/auth/login", tags=["auth"])
def login(body: Login, request: Request) -> dict[str, Any]:
    try:
        s = get_sessions(request).login(body.username, body.password)
    except AuthError as e:
        raise HTTPException(401, str(e)) from e
    return {"session_token": s.token, "user": s.as_dict(), "idle_seconds": get_sessions(request).idle_seconds}


@router.post("/auth/logout", tags=["auth"])
def logout(request: Request, s: Session = Viewer) -> dict[str, Any]:
    get_sessions(request).logout(s.token)
    return {"ok": True}


@router.get("/auth/me", tags=["auth"])
def me(s: Session = Viewer) -> dict[str, Any]:
    return s.as_dict()


@router.post("/auth/ping", tags=["auth"])
def ping(s: Session = Viewer) -> dict[str, Any]:
    """Keeps the session alive while the user is active (UI calls this on input)."""
    return {"ok": True}


# ====================================================================== users
class NewUser(BaseModel):
    username: str = Field(min_length=2, max_length=64)
    display_name: str
    role: Literal["ADMIN", "REVIEWER", "VIEWER"]
    password: str = Field(min_length=10)


class PatchUser(BaseModel):
    display_name: str | None = None
    role: Literal["ADMIN", "REVIEWER", "VIEWER"] | None = None
    active: bool | None = None
    password: str | None = Field(None, min_length=10)


@router.get("/users", tags=["users"])
def list_users(request: Request, s: Session = Admin) -> list[dict[str, Any]]:
    return E(request).db.query("SELECT id, username, display_name, role, active, last_login_at FROM users ORDER BY id")


@router.post("/users", tags=["users"])
def add_user(body: NewUser, request: Request, s: Session = Admin) -> dict[str, Any]:
    try:
        uid = create_user(E(request).db, body.username, body.display_name, body.role, body.password, actor_id=s.user_id)
    except Exception as e:  # noqa: BLE001
        raise HTTPException(400, f"could not create user: {type(e).__name__}") from e
    return {"id": uid}


@router.patch("/users/{uid}", tags=["users"])
def patch_user(uid: int, body: PatchUser, request: Request, s: Session = Admin) -> dict[str, Any]:
    from invoice_analytics.security.passwords import hash_password

    eng = E(request)
    before = eng.db.one("SELECT id, display_name, role, active FROM users WHERE id=?", (uid,))
    if before is None:
        raise HTTPException(404, "user not found")
    sets, vals = [], []
    for k in ("display_name", "role", "active"):
        v = getattr(body, k)
        if v is not None:
            sets.append(f"{k}=?")
            vals.append(int(v) if isinstance(v, bool) else v)
    if body.password:
        sets.append("password_hash=?")
        vals.append(hash_password(body.password))
    if sets:
        with eng.db.tx() as c:
            c.execute(
                f"UPDATE users SET {', '.join(sets)}, updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id=?",
                [*vals, uid],
            )
            audit.record(
                eng.db,
                "USER_UPDATE",
                user_id=s.user_id,
                entity_type="user",
                entity_id=uid,
                before=before,
                after={k: getattr(body, k) for k in ("display_name", "role", "active")}
                | {"password_changed": bool(body.password)},
                conn=c,
            )
    return {"ok": True}


# ====================================================================== ingest
@router.post("/ingest/files", tags=["ingest"])
async def ingest_files(
    request: Request,
    files: list[UploadFile] = File(...),
    options: str = Form("{}"),
    template_id: int | None = Form(None),
    mapping: str | None = Form(None),
    s: Session = Reviewer,
) -> dict[str, Any]:
    jobs = request.app.state.ingest_jobs
    opts = json.loads(options or "{}")
    mp = json.loads(mapping) if mapping else None
    out = []
    for f in files:
        data = await f.read()
        out.append(
            jobs.submit(
                f.filename or "upload", data, user_id=s.user_id, options=opts, mapping=mp, template_id=template_id
            ).public()
        )
    return {"jobs": out}


@router.get("/ingest/jobs", tags=["ingest"])
def ingest_jobs(request: Request, s: Session = Viewer) -> list[dict[str, Any]]:
    return request.app.state.ingest_jobs.list()  # type: ignore[no-any-return]


@router.get("/ingest/jobs/{job_id}", tags=["ingest"])
def ingest_job(job_id: int, request: Request, s: Session = Viewer) -> dict[str, Any]:
    j = request.app.state.ingest_jobs.get(job_id)
    if j is None:
        raise HTTPException(404, "job not found")
    return j.public()  # type: ignore[no-any-return]


class MappingSubmit(BaseModel):
    mapping: dict[str, str]
    options: dict[str, Any] = {}
    save_template_name: str | None = None


@router.post("/ingest/jobs/{job_id}/mapping", tags=["ingest"])
def ingest_job_mapping(job_id: int, body: MappingSubmit, request: Request, s: Session = Reviewer) -> dict[str, Any]:
    from invoice_analytics.ingest.service import save_template

    jobs = request.app.state.ingest_jobs
    j = jobs.get(job_id)
    if j is None:
        raise HTTPException(404, "job not found or expired")
    tid = None
    if body.save_template_name:
        headers = (j.result or {}).get("headers")
        tid = save_template(E(request), body.save_template_name, headers, body.mapping, body.options, s.user_id)
    return jobs.resubmit_with_mapping(job_id, body.mapping, body.options, tid).public()  # type: ignore[no-any-return]


class Template(BaseModel):
    name: str
    headers: list[str] | None = None
    mapping: dict[str, str]
    options: dict[str, Any] = {}


@router.post("/ingest/csv/mapping-templates", tags=["ingest"])
def add_template(body: Template, request: Request, s: Session = Reviewer) -> dict[str, Any]:
    from invoice_analytics.ingest.service import save_template

    return {"id": save_template(E(request), body.name, body.headers, body.mapping, body.options, s.user_id)}


@router.get("/ingest/csv/mapping-templates", tags=["ingest"])
def list_templates(request: Request, s: Session = Viewer) -> list[dict[str, Any]]:
    rows = E(request).db.query(
        "SELECT id, name, header_sig, mapping, options, updated_at FROM csv_mapping_templates ORDER BY name"
    )
    for r in rows:
        r["mapping"], r["options"] = json.loads(r["mapping"]), json.loads(r["options"])
    return rows


@router.get("/ingest/csv/fields", tags=["ingest"])
def csv_fields(s: Session = Viewer) -> dict[str, Any]:
    from invoice_analytics.ingest.csv.importer import HEADER_FIELDS, LINE_FIELDS, REQUIRED

    return {"header_fields": HEADER_FIELDS, "line_fields": LINE_FIELDS, "required": REQUIRED}


@router.post("/ingest/watch/scan", tags=["ingest"])
def watch_scan(request: Request, s: Session = Reviewer) -> dict[str, Any]:
    return {"queued": request.app.state.ingest_jobs.scan_once()}


# ====================================================================== documents / extraction drafts
@router.get("/documents", tags=["documents"])
def documents(
    request: Request, status: str | None = None, limit: int = Query(100, le=500), s: Session = Viewer
) -> list[dict[str, Any]]:
    return E(request).db.query(
        "SELECT d.id, d.source_path, d.mime, d.page_count, d.ingest_method, d.ingest_status, d.ingest_confidence,"
        " d.ingested_at, (SELECT id FROM extraction_drafts x WHERE x.document_id=d.id ORDER BY id DESC LIMIT 1) AS draft_id,"
        " (SELECT COUNT(*) FROM invoices i WHERE i.document_id=d.id) AS invoices"
        " FROM documents d WHERE (? IS NULL OR d.ingest_status=?) ORDER BY d.id DESC LIMIT ?",
        (status, status, limit),
    )


@router.get("/documents/{doc_id}/content", tags=["documents"])
def document_content(doc_id: int, request: Request, s: Session = Reviewer) -> Response:
    eng = E(request)
    row = eng.db.one(
        "SELECT b.data, d.mime FROM document_blobs b JOIN documents d ON d.id=b.document_id WHERE b.document_id=?",
        (doc_id,),
    )
    if row is None:
        raise HTTPException(404, "no stored content for this document")
    audit.record(eng.db, "VIEW_PHI", user_id=s.user_id, entity_type="document", entity_id=doc_id)
    media = "application/pdf" if row["mime"] == "PDF" else "image/png"
    return Response(row["data"], media_type=media, headers={"Cache-Control": "no-store"})


@router.get("/drafts/{draft_id}", tags=["documents"])
def get_draft(draft_id: int, request: Request, s: Session = Reviewer) -> dict[str, Any]:
    eng = E(request)
    d = eng.db.one("SELECT * FROM extraction_drafts WHERE id=?", (draft_id,))
    if d is None:
        raise HTTPException(404, "draft not found")
    d["fields"] = json.loads(d["fields"])
    ai = eng.db.one(
        "SELECT id, status, output, created_at FROM ai_suggestions WHERE target_type='EXTRACTION_DRAFT'"
        " AND target_id=? ORDER BY id DESC LIMIT 1",
        (draft_id,),
    )
    if ai:
        ai["output"] = _j(ai["output"])
    d["ai_suggestion"] = ai
    audit.record(eng.db, "VIEW_PHI", user_id=s.user_id, entity_type="extraction_draft", entity_id=draft_id)
    return d


class DraftAccept(BaseModel):
    invoice: dict[str, Any] = {}
    lines: list[dict[str, Any]] | None = None
    options: dict[str, Any] = {}
    from_ai: bool = False


@router.post("/drafts/{draft_id}/accept", tags=["documents"])
def accept_draft_ep(draft_id: int, body: DraftAccept, request: Request, s: Session = Reviewer) -> dict[str, Any]:
    from invoice_analytics.ingest.pdf.pipeline import accept_draft

    corrected: dict[str, Any] = {"invoice": body.invoice, "from_ai": body.from_ai}
    if body.lines is not None:
        corrected["lines"] = body.lines
    try:
        return accept_draft(E(request), draft_id, corrected, user_id=s.user_id, options=body.options)
    except ValueError as e:
        raise HTTPException(400, str(e)) from e


@router.post("/drafts/{draft_id}/reject", tags=["documents"])
def reject_draft(draft_id: int, request: Request, s: Session = Reviewer) -> dict[str, Any]:
    eng = E(request)
    with eng.db.tx() as c:
        n = c.execute(
            "UPDATE extraction_drafts SET status='REJECTED' WHERE id=? AND status='OPEN'", (draft_id,)
        ).rowcount
        audit.record(
            eng.db, "EXTRACTION_REJECT", user_id=s.user_id, entity_type="extraction_draft", entity_id=draft_id, conn=c
        )
    return {"ok": bool(n)}


# ====================================================================== invoices
@router.get("/invoices", tags=["invoices"])
def invoices(
    request: Request,
    party_id: int | None = None,
    q: str | None = None,
    status: str | None = None,
    date_from: str | None = Query(None, alias="from"),
    date_to: str | None = Query(None, alias="to"),
    min_cents: int | None = None,
    max_cents: int | None = None,
    direction: str | None = None,
    flagged: bool | None = None,
    limit: int = Query(100, le=1000),
    offset: int = 0,
    s: Session = Viewer,
) -> dict[str, Any]:
    where: list[str] = ["i.deleted_at IS NULL"]
    p: list[Any] = []
    if party_id:
        where.append("p.cluster_id=(SELECT cluster_id FROM parties WHERE id=?)")
        p.append(party_id)
    if q:
        from invoice_analytics.normalize import normalize_invoice_number

        where.append("(i.invoice_number_norm LIKE ? OR p.name_norm LIKE ? OR i.po_number LIKE ?)")
        p += [f"%{normalize_invoice_number(q) or q}%", f"%{q.upper()}%", f"%{q}%"]
    for col, val, op in (
        ("i.status", status, "="),
        ("i.invoice_date", date_from, ">="),
        ("i.invoice_date", date_to, "<="),
        ("i.total_cents", min_cents, ">="),
        ("i.total_cents", max_cents, "<="),
        ("i.direction", direction, "="),
    ):
        if val is not None:
            where.append(f"{col}{op}?")
            p.append(val)
    if flagged is not None:
        where.append(
            ("" if flagged else "NOT ") + "EXISTS (SELECT 1 FROM flags f WHERE f.subject_invoice_id=i.id AND f.active=1"
            " AND f.suppressed_by IS NULL AND f.tier IN ('HARD','PROBABLE'))"
        )
    w = " AND ".join(where)
    eng = E(request)
    total = eng.db.scalar(f"SELECT COUNT(*) FROM invoices i JOIN parties p ON p.id=i.party_id WHERE {w}", p)
    rows = eng.db.query(
        f"SELECT i.id, i.direction, i.party_id, p.display_name AS party, i.invoice_number_raw AS invoice_number,"
        f" i.invoice_date, i.invoice_date_raw, i.total_cents, i.status, i.claim_frequency_code, i.needs_attention,"
        f" (SELECT COUNT(*) FROM invoice_lines l WHERE l.invoice_id=i.id) AS line_count,"
        f" (SELECT MAX(CASE f.tier WHEN 'HARD' THEN 4 WHEN 'PROBABLE' THEN 3 WHEN 'WEAK' THEN 2 ELSE 1 END) FROM flags f"
        f"  WHERE f.subject_invoice_id=i.id AND f.active=1 AND f.suppressed_by IS NULL) AS max_tier_rank"
        f" FROM invoices i JOIN parties p ON p.id=i.party_id WHERE {w} ORDER BY i.invoice_date DESC, i.id DESC"
        f" LIMIT ? OFFSET ?",
        [*p, limit, offset],
    )
    return {"total": total, "items": rows}


def invoice_detail(eng: Engine, invoice_id: int, user_id: int | None) -> dict[str, Any]:
    inv = eng.db.one(
        "SELECT i.*, p.display_name AS party, p.cluster_id AS party_cluster, d.source_path, d.ingest_method, d.sha256"
        " FROM invoices i JOIN parties p ON p.id=i.party_id LEFT JOIN documents d ON d.id=i.document_id WHERE i.id=?",
        (invoice_id,),
    )
    if inv is None:
        raise HTTPException(404, "invoice not found")
    fc = eng.field_cipher
    lines = eng.db.query(
        "SELECT l.*, pt.cluster_id AS patient_cluster, pt.first_name_enc, pt.last_name_enc, pt.dob AS patient_dob,"
        " pt.subject_id_enc"
        " FROM invoice_lines l LEFT JOIN patients pt ON pt.id=l.patient_id WHERE l.invoice_id=? ORDER BY l.line_no",
        (invoice_id,),
    )
    for li in lines:
        first = fc.decrypt(li.pop("first_name_enc"), aad="patient.first") if li.get("first_name_enc") else None
        last = fc.decrypt(li.pop("last_name_enc"), aad="patient.last") if li.get("last_name_enc") else None
        li.pop("first_name_enc", None)
        li.pop("last_name_enc", None)
        li.pop("description_embedding", None)
        subj = fc.decrypt(li.pop("subject_id_enc"), aad="patient.subject") if li.get("subject_id_enc") else None
        li.pop("subject_id_enc", None)
        li["patient_name"] = (
            f"{last}, {first}".strip(", ") if (first or last) else (f"Subject {subj}" if subj else None)
        )
        li["modifiers"] = json.loads(li["modifiers"])
        li["dx_codes"] = json.loads(li["dx_codes"])
    inv["lines"] = lines
    inv["flags"] = eng.db.query(
        "SELECT id, rule_id, tier, status, score, suppressed_by, amount_at_risk_cents, subject_type,"
        " json_extract(evidence,'$.summary') AS summary FROM flags WHERE active=1 AND"
        " (subject_invoice_id=? OR EXISTS (SELECT 1 FROM json_each(counterpart_invoice_ids) WHERE value=?))"
        " ORDER BY CASE tier WHEN 'HARD' THEN 0 WHEN 'PROBABLE' THEN 1 WHEN 'WEAK' THEN 2 ELSE 3 END",
        (invoice_id, invoice_id),
    )
    inv["links"] = eng.db.query(
        "SELECT * FROM invoice_links WHERE from_invoice_id=? OR to_invoice_id=?", (invoice_id, invoice_id)
    )
    inv["history"] = [
        audit.decode(r)
        for r in eng.db.query(
            "SELECT ts, action, user_id, after FROM audit_log WHERE entity_type='invoice' AND entity_id=? ORDER BY id",
            (str(invoice_id),),
        )
    ]
    audit.record(eng.db, "VIEW_PHI", user_id=user_id, entity_type="invoice", entity_id=invoice_id)
    return inv


@router.get("/invoices/{invoice_id}", tags=["invoices"])
def get_invoice(invoice_id: int, request: Request, s: Session = Viewer) -> dict[str, Any]:
    return invoice_detail(E(request), invoice_id, s.user_id)


@router.delete("/invoices/{invoice_id}", tags=["invoices"])
def delete_invoice(invoice_id: int, request: Request, s: Session = Admin) -> dict[str, Any]:
    """Permanently delete one invoice with its lines, source document and every flag involving it."""
    from invoice_analytics.data_admin import delete_invoices

    try:
        return delete_invoices(E(request), [invoice_id], user_id=s.user_id)
    except KeyError as e:
        raise HTTPException(404, "invoice not found") from e


class DeleteInvoicesBody(BaseModel):
    invoice_ids: list[int] = Field(min_length=1, max_length=10_000)


@router.post("/invoices/delete", tags=["invoices"])
def delete_selected_invoices(body: DeleteInvoicesBody, request: Request, s: Session = Admin) -> dict[str, Any]:
    """Permanently delete the selected invoices (see DELETE /invoices/{id})."""
    from invoice_analytics.data_admin import delete_invoices

    try:
        return delete_invoices(E(request), body.invoice_ids, user_id=s.user_id)
    except KeyError as e:
        raise HTTPException(404, "invoice not found") from e


class DeleteAllBody(BaseModel):
    confirm: str


@router.post("/data/delete-all", tags=["invoices"])
def delete_all_invoices(body: DeleteAllBody, request: Request, s: Session = Admin) -> dict[str, Any]:
    """Start fresh: delete every invoice, document and flag. Settings, users and templates stay."""
    from invoice_analytics.data_admin import delete_invoices

    if body.confirm != "DELETE":
        raise HTTPException(400, "type DELETE to confirm")
    return delete_invoices(E(request), None, user_id=s.user_id)


# ====================================================================== flags / review
_TIER_ORDER = "CASE f.tier WHEN 'HARD' THEN 0 WHEN 'PROBABLE' THEN 1 WHEN 'WEAK' THEN 2 ELSE 3 END"


def _flag_filters(
    tier: str | None,
    rule: str | None,
    status: str | None,
    party: int | None,
    date_from: str | None,
    date_to: str | None,
    include_suppressed: bool,
    min_cents: int | None,
) -> tuple[str, list[Any]]:
    where: list[str] = ["f.active=1"]
    p: list[Any] = []
    if not include_suppressed:
        where.append("f.suppressed_by IS NULL")
    if tier:
        tiers = tier.split(",")
        where.append(f"f.tier IN ({','.join('?' * len(tiers))})")
        p += tiers
    else:
        where.append("f.tier IN ('HARD','PROBABLE')")
    if rule:
        rules = rule.split(",")
        where.append(f"f.rule_id IN ({','.join('?' * len(rules))})")
        p += rules
    if status:
        sts = status.split(",")
        where.append(f"f.status IN ({','.join('?' * len(sts))})")
        p += sts
    if party:
        where.append(
            "f.party_id IN (SELECT id FROM parties WHERE cluster_id=(SELECT cluster_id FROM parties WHERE id=?))"
        )
        p.append(party)
    if date_from:
        where.append("i.invoice_date>=?")
        p.append(date_from)
    if date_to:
        where.append("i.invoice_date<=?")
        p.append(date_to)
    if min_cents is not None:
        where.append("f.amount_at_risk_cents>=?")
        p.append(min_cents)
    return " AND ".join(where), p


# What a flag compares the record with: another invoice (billed before), lines of the same invoice,
# or nothing (a limit breached on one record). Cross-invoice flags are reviewed first.
_SCOPE_SQL = (
    "(CASE WHEN f.counterpart_invoice_ids IN ('[]', '') THEN 'SINGLE'"
    " WHEN json(f.counterpart_invoice_ids) = json_array(f.subject_invoice_id) THEN 'WITHIN' ELSE 'ACROSS' END)"
)
_SCOPE_ORDER = f"CASE {_SCOPE_SQL} WHEN 'ACROSS' THEN 0 WHEN 'SINGLE' THEN 1 ELSE 2 END"


@router.get("/flags", tags=["flags"])
def flags(
    request: Request,
    tier: str | None = None,
    rule: str | None = None,
    status: str | None = "OPEN",
    party: int | None = None,
    date_from: str | None = Query(None, alias="from"),
    date_to: str | None = Query(None, alias="to"),
    sort: str = "priority",
    include_suppressed: bool = False,
    min_cents: int | None = None,
    scope: Literal["ACROSS", "WITHIN", "SINGLE"] | None = None,
    limit: int = Query(200, le=2000),
    offset: int = 0,
    s: Session = Viewer,
) -> dict[str, Any]:
    w, p = _flag_filters(tier, rule, status, party, date_from, date_to, include_suppressed, min_cents)
    if scope:
        w += f" AND {_SCOPE_SQL} = ?"
        p.append(scope)
    order = {
        "priority": f"{_TIER_ORDER}, {_SCOPE_ORDER}, f.score DESC, f.amount_at_risk_cents DESC",
        "amount": "f.amount_at_risk_cents DESC",
        "newest": "f.id DESC",
        "date": "i.invoice_date DESC",
    }.get(sort, _TIER_ORDER)
    eng = E(request)
    total = eng.db.scalar(f"SELECT COUNT(*) FROM flags f JOIN invoices i ON i.id=f.subject_invoice_id WHERE {w}", p)
    rows = eng.db.query(
        f"SELECT f.id, f.rule_id, f.tier, f.base_tier, f.score, f.status, f.subject_type, f.subject_id, f.subject_invoice_id,"
        f" f.counterpart_invoice_ids, f.amount_at_risk_cents, f.suppressed_by, f.downgraded_by, f.created_at,"
        f" json_extract(f.evidence,'$.summary') AS summary, json_extract(f.evidence,'$.title') AS title,"
        f" i.invoice_number_raw AS invoice_number, i.invoice_date, pa.display_name AS party, {_SCOPE_SQL} AS scope,"
        f" (SELECT COUNT(*) FROM flags s WHERE s.subject_invoice_id=f.subject_invoice_id AND s.id<>f.id"
        f"  AND s.counterpart_invoice_ids=f.counterpart_invoice_ids AND s.active=1 AND s.suppressed_by IS NULL"
        f"  AND s.status=f.status) AS sibling_count,"
        f" (SELECT json_extract(output,'$.verdict') FROM ai_suggestions a WHERE a.target_type='FLAG' AND a.target_id=f.id"
        f"  AND a.task='TRIAGE' AND a.status='OK' ORDER BY a.id DESC LIMIT 1) AS ai_verdict"
        f" FROM flags f JOIN invoices i ON i.id=f.subject_invoice_id JOIN parties pa ON pa.id=i.party_id"
        f" WHERE {w} ORDER BY {order} LIMIT ? OFFSET ?",
        [*p, limit, offset],
    )
    for r in rows:
        r["counterpart_invoice_ids"] = json.loads(r["counterpart_invoice_ids"])
    return {"total": total, "items": rows}


@router.get("/flags/export.csv", tags=["flags"])
def flags_export(
    request: Request, tier: str | None = None, rule: str | None = None, status: str | None = None, s: Session = Viewer
) -> Response:
    from invoice_analytics.reports import to_csv

    eng = E(request)
    w, p = _flag_filters(tier, rule, status, None, None, None, False, None)
    rows = eng.db.query(
        f"SELECT f.id AS flag_id, f.rule_id, f.tier, f.status, f.score, pa.display_name AS party,"
        f" i.invoice_number_raw AS invoice_number, i.invoice_date, f.amount_at_risk_cents,"
        f" json_extract(f.evidence,'$.summary') AS summary FROM flags f JOIN invoices i ON i.id=f.subject_invoice_id"
        f" JOIN parties pa ON pa.id=i.party_id WHERE {w} ORDER BY {_TIER_ORDER}, f.score DESC",
        p,
    )
    audit.record(eng.db, "EXPORT", user_id=s.user_id, entity_type="flags", after={"rows": len(rows), "format": "csv"})
    return Response(
        to_csv(rows),
        media_type="text/csv",
        headers={"Content-Disposition": "attachment; filename=invoice-analytics-flags.csv"},
    )


@router.get("/flags/reasons", tags=["flags"])
def reasons(s: Session = Viewer) -> dict[str, list[str]]:
    from invoice_analytics.review import REASON_CODES

    return REASON_CODES


@router.get("/flags/{flag_id}", tags=["flags"])
def flag_detail(flag_id: int, request: Request, s: Session = Viewer) -> dict[str, Any]:
    from invoice_analytics.review import history

    eng = E(request)
    f = eng.db.one("SELECT * FROM flags WHERE id=?", (flag_id,))
    if f is None:
        raise HTTPException(404, "flag not found")
    f["evidence"] = json.loads(f["evidence"])
    f["counterpart_ids"] = json.loads(f["counterpart_ids"])
    f["counterpart_invoice_ids"] = json.loads(f["counterpart_invoice_ids"])
    f["subject_invoice"] = invoice_detail(eng, f["subject_invoice_id"], s.user_id)
    f["counterpart_invoices"] = [invoice_detail(eng, i, s.user_id) for i in f["counterpart_invoice_ids"][:4]]
    f["reviews"] = history(eng, flag_id)
    sugg = eng.db.query(
        "SELECT id, task, status, output, model_id, prompt_version, latency_ms, created_at"
        " FROM ai_suggestions WHERE target_type='FLAG' AND target_id=? ORDER BY id DESC",
        (flag_id,),
    )
    for a in sugg:
        a["output"] = _j(a["output"])
    f["ai"] = {
        "explain": next((a for a in sugg if a["task"] == "EXPLAIN"), None),
        "triage": next((a for a in sugg if a["task"] == "TRIAGE"), None),
    }
    f["other_flags_on_subject"] = eng.db.query(
        "SELECT id, rule_id, tier, status FROM flags WHERE subject_invoice_id=? AND id<>? AND active=1 AND suppressed_by IS NULL",
        (f["subject_invoice_id"], flag_id),
    )
    # opening a flag bumps its explanation to the front of the AI queue
    if eng.settings.get("ai.tier", "OFF") != "OFF" and f["ai"]["explain"] is None:
        from invoice_analytics.ai.jobs import PRIORITY

        eng.jobs.enqueue("AI_EXPLAIN", {"flag_id": flag_id}, PRIORITY["UI_EXPLAIN"])
    return f


class ReviewBody(BaseModel):
    decision: Literal["CONFIRMED_DUPLICATE", "NOT_DUPLICATE", "NEEDS_INFO"]
    reason_code: str | None = None
    note: str | None = Field(None, max_length=2000)
    recovered_cents: int | None = None
    apply_to_siblings: bool = True


@router.post("/flags/{flag_id}/review", tags=["flags"])
def review(flag_id: int, body: ReviewBody, request: Request, s: Session = Reviewer) -> dict[str, Any]:
    from invoice_analytics.review import ReviewError, decide

    try:
        return decide(
            E(request),
            flag_id,
            body.decision,
            s.user_id,
            reason_code=body.reason_code,
            note=body.note,
            recovered_cents=body.recovered_cents,
            apply_to_siblings=body.apply_to_siblings,
        )
    except ReviewError as e:
        raise HTTPException(400, str(e)) from e


# ====================================================================== detection
@router.post("/detect/sweep", tags=["detect"])
def sweep(request: Request, s: Session = Reviewer) -> dict[str, Any]:
    return {"job_id": E(request).jobs.enqueue("DETECT_SWEEP", {"user_id": s.user_id, "reload": True}, 10)}


@router.get("/detect/sweep/{job_id}", tags=["detect"])
def sweep_status(job_id: int, request: Request, s: Session = Viewer) -> dict[str, Any]:
    j = E(request).jobs.get(job_id)
    if j is None:
        raise HTTPException(404, "job not found")
    return j


@router.get("/detect/runs", tags=["detect"])
def runs(request: Request, s: Session = Viewer) -> list[dict[str, Any]]:
    rows = E(request).db.query("SELECT * FROM detection_runs ORDER BY id DESC LIMIT 50")
    for r in rows:
        r["stats"] = _j(r["stats"])
    return rows


# ====================================================================== parties / patients
@router.get("/parties", tags=["identity"])
def parties(
    request: Request, q: str | None = None, limit: int = Query(200, le=2000), s: Session = Viewer
) -> list[dict[str, Any]]:
    return E(request).db.query(
        "SELECT p.id, p.party_type, p.display_name, p.name_norm, p.npi, p.cluster_id, p.active,"
        " (SELECT COUNT(*) FROM invoices i WHERE i.party_id=p.id) AS invoices,"
        " (SELECT COUNT(*) FROM party_aliases a WHERE a.party_id=p.id) AS aliases"
        " FROM parties p WHERE (? IS NULL OR p.name_norm LIKE ?) ORDER BY p.cluster_id, p.id LIMIT ?",
        (q, f"%{(q or '').upper()}%", limit),
    )


def _suggestions(eng: Engine, entity: str, status: str) -> list[dict[str, Any]]:
    rows = eng.db.query(
        "SELECT * FROM identity_suggestions WHERE entity_type=? AND status=? ORDER BY match_probability DESC"
        " LIMIT 500",
        (entity, status),
    )
    for r in rows:
        r["evidence"] = json.loads(r["evidence"])
    return rows


@router.get("/parties/merge-suggestions", tags=["identity"])
def party_suggestions(request: Request, status: str = "OPEN", s: Session = Viewer) -> list[dict[str, Any]]:
    eng = E(request)
    rows = _suggestions(eng, "PARTY", status)
    names = {r["id"]: r for r in eng.db.query("SELECT id, display_name, remit_address_norm, npi FROM parties")}
    for r in rows:
        r["left"], r["right"] = names.get(r["left_id"]), names.get(r["right_id"])
    return rows


class Pair(BaseModel):
    left_id: int
    right_id: int


@router.post("/parties/merge", tags=["identity"])
def party_merge(body: Pair, request: Request, s: Session = Admin) -> dict[str, Any]:
    from invoice_analytics.linkage.parties import merge

    merge(E(request), body.left_id, body.right_id, s.user_id)
    return {"ok": True}


@router.post("/parties/unmerge", tags=["identity"])
def party_unmerge(body: Pair, request: Request, s: Session = Admin) -> dict[str, Any]:
    from invoice_analytics.linkage.parties import unmerge

    unmerge(E(request), body.left_id, body.right_id, s.user_id)
    return {"ok": True}


@router.post("/identity/resolve", tags=["identity"])
def resolve(request: Request, s: Session = Reviewer) -> dict[str, Any]:
    return {"job_id": E(request).jobs.enqueue("LINKAGE", {"user_id": s.user_id, "then_sweep": True}, 15)}


@router.get("/patients/link-suggestions", tags=["identity"])
def patient_suggestions(
    request: Request, status: str = "OPEN", show_names: bool = False, s: Session = Reviewer
) -> list[dict[str, Any]]:
    eng = E(request)
    rows = _suggestions(eng, "PATIENT", status)
    if show_names:
        fc = eng.field_cipher
        ids = {i for r in rows for i in (r["left_id"], r["right_id"])}
        if ids:
            ph = ",".join("?" * len(ids))
            pts = {
                p["id"]: p
                for p in eng.db.query(
                    f"SELECT id, first_name_enc, last_name_enc, dob, sex, zip5 FROM patients WHERE id IN ({ph})",
                    list(ids),
                )
            }
            for r in rows:
                for side in ("left", "right"):
                    p = pts.get(r[f"{side}_id"], {})
                    r[side] = {
                        "name": f"{fc.decrypt(p.get('last_name_enc'), aad='patient.last') or ''}, "
                        f"{fc.decrypt(p.get('first_name_enc'), aad='patient.first') or ''}",
                        "dob": p.get("dob"),
                        "sex": p.get("sex"),
                        "zip5": p.get("zip5"),
                    }
            audit.record(
                eng.db,
                "VIEW_PHI",
                user_id=s.user_id,
                entity_type="patient_link_suggestions",
                after={"pairs": len(rows)},
            )
    return rows


@router.post("/patients/link", tags=["identity"])
def patient_link(body: Pair, request: Request, s: Session = Reviewer) -> dict[str, Any]:
    from invoice_analytics.linkage.patients import set_link

    set_link(E(request), body.left_id, body.right_id, link=True, user_id=s.user_id)
    return {"ok": True}


@router.post("/patients/unlink", tags=["identity"])
def patient_unlink(body: Pair, request: Request, s: Session = Reviewer) -> dict[str, Any]:
    from invoice_analytics.linkage.patients import set_link

    set_link(E(request), body.left_id, body.right_id, link=False, user_id=s.user_id)
    return {"ok": True}


# ====================================================================== rules
@router.get("/rules", tags=["rules"])
def rules(request: Request, s: Session = Viewer) -> list[dict[str, Any]]:
    from invoice_analytics.reports import rule_precision
    from invoice_analytics.rules import ALL_RULES

    eng = E(request)
    prec = {r["rule_id"]: r for r in rule_precision(eng)}
    counts = {
        r["rule_id"]: r["n"]
        for r in eng.db.query(
            "SELECT rule_id, COUNT(*) AS n FROM flags WHERE active=1 AND suppressed_by IS NULL GROUP BY rule_id"
        )
    }
    out = []
    for r in ALL_RULES:
        key = f"rules.{r.rule_id}"
        out.append(
            {
                **r.describe(),
                "config": eng.settings.get(key),
                "config_version": eng.settings.version(key),
                "active_flags": counts.get(r.rule_id, 0),
                "precision": prec[r.rule_id]["precision"],
                "reviewed": prec[r.rule_id]["reviewed"],
            }
        )
    sups = [
        {"rule_id": k.split(".", 1)[1], "config": v} for k, v in eng.settings.all().items() if k.startswith("suppress.")
    ]
    return out + [{"rule_id": x["rule_id"], "kind": "suppression", "config": x["config"]} for x in sups]


@router.patch("/rules/{rule_id}", tags=["rules"])
def patch_rule(rule_id: str, changes: dict[str, Any], request: Request, s: Session = Admin) -> dict[str, Any]:
    eng = E(request)
    key = f"suppress.{rule_id}" if rule_id.startswith("SUP-") else f"rules.{rule_id}"
    if eng.settings.get(key) is None:
        raise HTTPException(404, "unknown rule")
    allowed = set(eng.settings.get(key).keys())
    bad = set(changes) - allowed
    if bad:
        raise HTTPException(400, f"unknown settings: {sorted(bad)}")
    ver = eng.settings.set(key, changes, s.user_id)
    return {
        "rule_id": rule_id,
        "version": ver,
        "config": eng.settings.get(key),
        "note": "Run a full sweep to apply the change to existing records.",
    }


class ImpactBody(BaseModel):
    changes: dict[str, dict[str, Any]]  # {"rules.INV-005": {"window_days": 30}}


@router.post("/rules/preview-impact", tags=["rules"])
def preview(body: ImpactBody, request: Request, s: Session = Reviewer) -> dict[str, Any]:
    from invoice_analytics.scoring.pipeline import preview_impact

    return preview_impact(E(request), body.changes)


# ====================================================================== reference data
@router.get("/refdata/versions", tags=["refdata"])
def refdata_versions(request: Request, s: Session = Viewer) -> list[dict[str, Any]]:
    from invoice_analytics.clinical.refdata import installed_versions

    return installed_versions(E(request))


@router.post("/refdata/import", tags=["refdata"])
async def refdata_import(request: Request, file: UploadFile = File(...), s: Session = Admin) -> dict[str, Any]:
    from invoice_analytics.clinical.refdata import RefdataError, import_bundle

    data = await file.read()
    try:
        return import_bundle(E(request), data, user_id=s.user_id)
    except RefdataError as e:
        audit.record(
            E(request).db, "REFDATA_IMPORT_REJECTED", user_id=s.user_id, entity_type="refdata", after={"reason": str(e)}
        )
        raise HTTPException(400, str(e)) from e


class FreqLimit(BaseModel):
    code: str
    max_count: int = Field(ge=1)
    period: Literal["DAY", "WEEK", "MONTH", "YEAR", "LIFETIME"]
    scope: Literal["PATIENT", "PATIENT_PROVIDER"] = "PATIENT"
    source: str | None = None
    note: str | None = None


class Recurring(BaseModel):
    code: str
    typical_frequency: str = Field(pattern=r"^(DAILY|WEEKLY|BIWEEKLY|MONTHLY|\dX_WEEK|EVERY_\d+D)$")
    note: str | None = None


def _ref_edit(
    eng: Engine, table: str, action: str, user_id: int, row: dict[str, Any] | None = None, rid: int | None = None
) -> dict[str, Any]:
    with eng.db.tx() as c:
        if action == "add" and row is not None:
            cols = list(row)
            rid = int(
                c.execute(
                    f"INSERT INTO {table}({','.join(cols)}) VALUES ({','.join('?' * len(cols))})",
                    [row[k] for k in cols],
                ).lastrowid
            )
        else:
            c.execute(f"DELETE FROM {table} WHERE id=?", (rid,))
        audit.record(
            eng.db,
            "REFDATA_EDIT",
            user_id=user_id,
            entity_type=table,
            entity_id=rid,
            after={"action": action, "row": row},
            conn=c,
        )
    eng.store.reload_refdata()
    return {"id": rid}


@router.get("/refdata/frequency-limits", tags=["refdata"])
def freq_limits(request: Request, s: Session = Viewer) -> list[dict[str, Any]]:
    return E(request).db.query("SELECT * FROM ref_frequency_limits ORDER BY code")


@router.post("/refdata/frequency-limits", tags=["refdata"])
def add_freq(body: FreqLimit, request: Request, s: Session = Admin) -> dict[str, Any]:
    return _ref_edit(
        E(request), "ref_frequency_limits", "add", s.user_id, {**body.model_dump(), "code": body.code.upper()}
    )


@router.delete("/refdata/frequency-limits/{rid}", tags=["refdata"])
def del_freq(rid: int, request: Request, s: Session = Admin) -> dict[str, Any]:
    return _ref_edit(E(request), "ref_frequency_limits", "delete", s.user_id, rid=rid)


@router.get("/refdata/recurring-series", tags=["refdata"])
def recurring(request: Request, s: Session = Viewer) -> list[dict[str, Any]]:
    return E(request).db.query("SELECT * FROM ref_recurring_series ORDER BY code")


@router.post("/refdata/recurring-series", tags=["refdata"])
def add_recurring(body: Recurring, request: Request, s: Session = Admin) -> dict[str, Any]:
    return _ref_edit(
        E(request), "ref_recurring_series", "add", s.user_id, {**body.model_dump(), "code": body.code.upper()}
    )


@router.delete("/refdata/recurring-series/{rid}", tags=["refdata"])
def del_recurring(rid: int, request: Request, s: Session = Admin) -> dict[str, Any]:
    return _ref_edit(E(request), "ref_recurring_series", "delete", s.user_id, rid=rid)


# ====================================================================== AI
@router.get("/ai/status", tags=["ai"])
def ai_status(request: Request, s: Session = Viewer) -> dict[str, Any]:
    from invoice_analytics.ai.service import status

    return status(E(request))


class TierBody(BaseModel):
    tier: Literal["OFF", "LITE", "STANDARD", "PLUS"]
    model_path: str | None = None


@router.post("/ai/tier", tags=["ai"])
def ai_tier(body: TierBody, request: Request, s: Session = Admin) -> dict[str, Any]:
    from invoice_analytics.ai import hardware

    eng = E(request)
    hw = hardware.detect()
    if body.tier != "OFF" and body.tier not in hw["eligible_tiers"]:
        raise HTTPException(400, f"this machine does not meet the {body.tier} requirements")
    if body.tier != "OFF":
        from invoice_analytics.ai.service import setup_state

        st = setup_state(eng)
        if not st["ready"]:
            raise HTTPException(400, "AI can't be switched on yet: " + "; ".join(st["missing"]) + ".")
    eng.settings.set("ai.tier", body.tier, s.user_id)
    if body.model_path is not None:
        eng.settings.set("ai.model_path", Path(body.model_path).name, s.user_id)
    if body.tier == "OFF" and "llm_runtime" in eng.extras:
        eng.extras["llm_runtime"].stop()
    return {"tier": body.tier}


def _require_ai(eng: Engine) -> None:
    from invoice_analytics.ai.service import setup_state

    if eng.settings.get("ai.tier", "OFF") == "OFF":
        raise HTTPException(409, "AI is switched off")
    st = setup_state(eng)
    if not st["ready"]:
        raise HTTPException(409, "AI can't run on this computer yet: " + "; ".join(st["missing"]) + ".")


@router.post("/ai/explain/{flag_id}", tags=["ai"])
def ai_explain(flag_id: int, request: Request, s: Session = Viewer) -> dict[str, Any]:
    from invoice_analytics.ai.jobs import PRIORITY

    eng = E(request)
    _require_ai(eng)
    return {"job_id": eng.jobs.enqueue("AI_EXPLAIN", {"flag_id": flag_id}, PRIORITY["USER"])}


@router.post("/ai/triage/{flag_id}", tags=["ai"])
def ai_triage(flag_id: int, request: Request, s: Session = Reviewer) -> dict[str, Any]:
    from invoice_analytics.ai.jobs import PRIORITY

    eng = E(request)
    _require_ai(eng)
    return {"job_id": eng.jobs.enqueue("AI_TRIAGE", {"flag_id": flag_id}, PRIORITY["USER"])}


class AskBody(BaseModel):
    question: str = Field(min_length=3, max_length=1000)


@router.post("/ai/ask", tags=["ai"])
def ai_ask(body: AskBody, request: Request, s: Session = Viewer) -> dict[str, Any]:
    from invoice_analytics.ai.jobs import PRIORITY

    eng = E(request)
    _require_ai(eng)
    return {
        "job_id": eng.jobs.enqueue(
            "AI_ASK", {"question": body.question, "user_id": s.user_id}, PRIORITY["USER"], dedupe=False
        )
    }


@router.get("/ai/suggestions/{sid}", tags=["ai"])
def ai_suggestion(sid: int, request: Request, s: Session = Viewer) -> dict[str, Any]:
    r = E(request).db.one("SELECT * FROM ai_suggestions WHERE id=?", (sid,))
    if r is None:
        raise HTTPException(404, "not found")
    r["output"], r["trace"] = _j(r["output"]), _j(r["trace"])
    return r


@router.get("/ai/jobs/{job_id}", tags=["ai"])
def ai_job(job_id: int, request: Request, s: Session = Viewer) -> dict[str, Any]:
    j = E(request).jobs.get(job_id)
    if j is None:
        raise HTTPException(404, "not found")
    return j


@router.post("/ai/jobs/{job_id}/cancel", tags=["ai"])
def ai_cancel(job_id: int, request: Request, s: Session = Viewer) -> dict[str, Any]:
    return {"cancelled": E(request).jobs.cancel(job_id)}


class ModelImport(BaseModel):
    path: str


@router.post("/ai/models/import", tags=["ai"])
def import_models(body: ModelImport, request: Request, s: Session = Admin) -> dict[str, Any]:
    from invoice_analytics.ai.models import import_model_package

    try:
        return import_model_package(E(request), Path(body.path), s.user_id)
    except ValueError as e:
        raise HTTPException(400, str(e)) from e


class SearchSQL(BaseModel):
    sql: str


@router.post("/search/sql", tags=["search"])
def run_sql(body: SearchSQL, request: Request, s: Session = Viewer) -> dict[str, Any]:
    """Run a reviewed read-only query (e.g. an edited AI-generated query). Same validator as T3."""
    from invoice_analytics.ai.tasks.nlq import UnsafeSQL, run_readonly

    try:
        return run_readonly(E(request), body.sql)
    except UnsafeSQL as e:
        raise HTTPException(400, str(e)) from e


@router.get("/search/schema", tags=["search"])
def search_schema(s: Session = Viewer) -> dict[str, Any]:
    from invoice_analytics.ai.tasks.nlq import VIEWS

    return VIEWS


# ====================================================================== reports / dashboard / audit
@router.get("/dashboard", tags=["reports"])
def dash(request: Request, s: Session = Viewer) -> dict[str, Any]:
    from invoice_analytics.reports import dashboard

    d = dashboard(E(request))
    d["ai"] = {"tier": E(request).settings.get("ai.tier"), "queue": E(request).jobs.status()}
    return d


@router.get("/reports/{name}", tags=["reports"])
def report(
    name: str,
    request: Request,
    format: str = "json",
    period: str = "month",
    date_from: str | None = Query(None, alias="from"),
    date_to: str | None = Query(None, alias="to"),
    s: Session = Viewer,
) -> Any:
    from invoice_analytics import reports as rp

    eng = E(request)
    if name not in rp.REPORTS:
        raise HTTPException(404, "unknown report")
    rows = rp.duplicates_by_period(eng, period, date_from, date_to) if name == "duplicates" else rp.REPORTS[name](eng)
    if format == "json":
        return rows
    audit.record(
        eng.db,
        "EXPORT",
        user_id=s.user_id,
        entity_type="report",
        entity_id=name,
        after={"format": format, "rows": len(rows)},
    )
    if format == "csv":
        return Response(
            rp.to_csv(rows),
            media_type="text/csv",
            headers={"Content-Disposition": f"attachment; filename=invoice-analytics-{name}.csv"},
        )
    if format == "pdf":
        return Response(
            rp.to_pdf(f"ABM Invoice Analytics report: {name}", rows),
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename=invoice-analytics-{name}.pdf"},
        )
    raise HTTPException(400, "format must be json, csv or pdf")


@router.get("/audit", tags=["audit"])
def audit_list(
    request: Request,
    action: str | None = None,
    entity_type: str | None = None,
    user_id: int | None = None,
    date_from: str | None = Query(None, alias="from"),
    date_to: str | None = Query(None, alias="to"),
    limit: int = Query(200, le=2000),
    offset: int = 0,
    s: Session = Admin,
) -> dict[str, Any]:
    where: list[str] = ["1=1"]
    p: list[Any] = []
    for col, v, op in (
        ("action", action, "="),
        ("entity_type", entity_type, "="),
        ("user_id", user_id, "="),
        ("ts", date_from, ">="),
        ("ts", date_to, "<="),
    ):
        if v is not None:
            where.append(f"a.{col}{op}?")
            p.append(v)
    eng = E(request)
    w = " AND ".join(where)
    rows = eng.db.query(
        f"SELECT a.*, u.username FROM audit_log a LEFT JOIN users u ON u.id=a.user_id WHERE {w}"
        f" ORDER BY a.id DESC LIMIT ? OFFSET ?",
        [*p, limit, offset],
    )
    return {
        "total": eng.db.scalar(f"SELECT COUNT(*) FROM audit_log a WHERE {w}", p),
        "items": [audit.decode(r) for r in rows],
    }


@router.post("/audit/verify", tags=["audit"])
def audit_verify(request: Request, s: Session = Admin) -> dict[str, Any]:
    eng = E(request)
    res = audit.verify(eng.db).as_dict()
    audit.record(eng.db, "AUDIT_VERIFY", user_id=s.user_id, entity_type="audit_log", after=res)
    return res


# ====================================================================== settings / backup / retention
@router.get("/settings", tags=["settings"])
def get_settings(request: Request, s: Session = Viewer) -> dict[str, Any]:
    return {k: v for k, v in E(request).settings.all().items() if not k.startswith(("rules.", "suppress."))}


@router.patch("/settings", tags=["settings"])
def patch_settings(changes: dict[str, Any], request: Request, s: Session = Admin) -> dict[str, Any]:
    eng = E(request)
    blocked = {"ai.tier"}  # use /ai/tier (hardware check)
    for k, v in changes.items():
        if k in blocked or k.startswith(("rules.", "suppress.")):
            raise HTTPException(400, f"{k} must be changed through its dedicated endpoint")
        if k == "ingest.watched_folders":
            v = [str(Path(x).expanduser()) for x in v if Path(x).expanduser().is_dir()]
        try:
            eng.settings.set(k, v, s.user_id)
        except KeyError as e:
            raise HTTPException(400, str(e)) from e
    if "security.session_idle_seconds" in changes:
        get_sessions(request).idle_seconds = int(changes["security.session_idle_seconds"])
    return {"ok": True}


class BackupBody(BaseModel):
    dest_dir: str | None = None
    recovery_key: str | None = None


@router.post("/backup", tags=["backup"])
def backup(body: BackupBody, request: Request, s: Session = Admin) -> dict[str, Any]:
    from invoice_analytics.backup import create_backup

    eng = E(request)
    dest = Path(body.dest_dir or eng.settings.get("backup.folder") or (eng.config.data_dir / "backups")).expanduser()
    out = create_backup(eng, dest, user_id=s.user_id, recovery_key=body.recovery_key)
    return {"path": str(out), "bytes": out.stat().st_size}


class RestoreBody(BaseModel):
    path: str
    recovery_key: str | None = None


@router.post("/restore", tags=["backup"])
def restore(body: RestoreBody, request: Request, s: Session = Admin) -> dict[str, Any]:
    import os
    import threading

    from invoice_analytics.backup import BackupError, restore_backup

    eng = E(request)
    p = Path(body.path).expanduser()
    if p.suffix != ".vbak" or not p.is_file():
        raise HTTPException(400, "choose a .vbak backup file")
    audit.record(eng.db, "RESTORE_START", user_id=s.user_id, entity_type="backup", entity_id=p.name)
    # Quiesce everything that holds a DB connection before the file is swapped (required on Windows).
    request.app.state.ingest_jobs.stop()
    try:
        res = restore_backup(eng, p, user_id=s.user_id, recovery_key=body.recovery_key)
    except BackupError as e:
        raise HTTPException(400, str(e)) from e
    # The engine exits after replying; the desktop shell restarts it on the restored database.
    threading.Timer(0.5, lambda: os._exit(75)).start()
    return {**res, "restart_required": True}


class RetentionBody(BaseModel):
    years: int = Field(ge=1, le=50)
    hard_delete: bool = False
    confirm: bool = False


@router.post("/retention/preview", tags=["backup"])
def retention_prev(body: RetentionBody, request: Request, s: Session = Admin) -> dict[str, Any]:
    from invoice_analytics.backup import retention_preview

    return retention_preview(E(request), body.years)


@router.post("/retention/apply", tags=["backup"])
def retention_apply_ep(body: RetentionBody, request: Request, s: Session = Admin) -> dict[str, Any]:
    from invoice_analytics.backup import retention_apply

    if not body.confirm:
        raise HTTPException(400, "set confirm=true to apply the retention action")
    return retention_apply(E(request), body.years, user_id=s.user_id, hard_delete=body.hard_delete)


@router.get("/jobs", tags=["system"])
def jobs(request: Request, s: Session = Viewer) -> list[dict[str, Any]]:
    rows = E(request).db.query(
        "SELECT id, kind, priority, status, attempts, error, created_at, started_at, finished_at"
        " FROM jobs ORDER BY id DESC LIMIT 100"
    )
    return rows
