-- 0002_seed_modifiers: modifier categories used by CLN-002, CLN-005, CLN-006 and SUP-006.
-- Modifier codes and their meanings are public CMS/NCCI information.
INSERT INTO ref_modifiers (modifier, category, ncci_bypass, description) VALUES
 ('59','DISTINCT',1,'Distinct procedural service'),
 ('XE','DISTINCT',1,'Separate encounter'),
 ('XS','DISTINCT',1,'Separate structure'),
 ('XP','DISTINCT',1,'Separate practitioner'),
 ('XU','DISTINCT',1,'Unusual non-overlapping service'),
 ('76','REPEAT',0,'Repeat procedure by same physician'),
 ('77','REPEAT',0,'Repeat procedure by another physician'),
 ('91','REPEAT',1,'Repeat clinical diagnostic laboratory test'),
 ('50','BILATERAL',0,'Bilateral procedure'),
 ('RT','BILATERAL',1,'Right side'),
 ('LT','BILATERAL',1,'Left side'),
 ('24','GLOBAL_BYPASS',1,'Unrelated E/M during postoperative period'),
 ('25','GLOBAL_BYPASS',1,'Significant, separately identifiable E/M'),
 ('57','GLOBAL_BYPASS',1,'Decision for surgery'),
 ('58','GLOBAL_BYPASS',1,'Staged or related procedure during postoperative period'),
 ('78','GLOBAL_BYPASS',1,'Unplanned return to OR during postoperative period'),
 ('79','GLOBAL_BYPASS',1,'Unrelated procedure during postoperative period'),
 ('27','OTHER',1,'Multiple outpatient hospital E/M encounters'),
 ('E1','OTHER',1,'Upper left eyelid'),('E2','OTHER',1,'Lower left eyelid'),
 ('E3','OTHER',1,'Upper right eyelid'),('E4','OTHER',1,'Lower right eyelid'),
 ('FA','OTHER',1,'Left hand, thumb'),('F1','OTHER',1,'Left hand, second digit'),
 ('F2','OTHER',1,'Left hand, third digit'),('F3','OTHER',1,'Left hand, fourth digit'),
 ('F4','OTHER',1,'Left hand, fifth digit'),('F5','OTHER',1,'Right hand, thumb'),
 ('F6','OTHER',1,'Right hand, second digit'),('F7','OTHER',1,'Right hand, third digit'),
 ('F8','OTHER',1,'Right hand, fourth digit'),('F9','OTHER',1,'Right hand, fifth digit'),
 ('TA','OTHER',1,'Left foot, great toe'),('T1','OTHER',1,'Left foot, second digit'),
 ('T2','OTHER',1,'Left foot, third digit'),('T3','OTHER',1,'Left foot, fourth digit'),
 ('T4','OTHER',1,'Left foot, fifth digit'),('T5','OTHER',1,'Right foot, great toe'),
 ('T6','OTHER',1,'Right foot, second digit'),('T7','OTHER',1,'Right foot, third digit'),
 ('T8','OTHER',1,'Right foot, fourth digit'),('T9','OTHER',1,'Right foot, fifth digit'),
 ('LC','OTHER',1,'Left circumflex coronary artery'),('LD','OTHER',1,'Left anterior descending coronary artery'),
 ('RC','OTHER',1,'Right coronary artery'),('LM','OTHER',1,'Left main coronary artery'),
 ('RI','OTHER',1,'Ramus intermedius coronary artery'),
 ('26','OTHER',0,'Professional component'),('TC','OTHER',0,'Technical component'),
 ('GP','OTHER',0,'Physical therapy plan of care'),('GO','OTHER',0,'Occupational therapy plan of care'),
 ('GN','OTHER',0,'Speech-language pathology plan of care'),('KX','OTHER',0,'Requirements met');
